version: "3"
  
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
      
volumes:
  data:
